export interface CmsArticle { id:string; slug:string; title:string; excerpt?:string|null; content?:string; status?:string; featured?:number; category?:string|null; category_slug?:string|null; author_name?:string|null; published_at?:string|null; updated_at:string; featured_image_url?:string|null; og_image_url?:string|null; seo_title?:string|null; seo_description?:string|null; canonical_url?:string|null }
const base = process.env.NEXT_PUBLIC_DUCKCLOUD_API_URL || 'https://api.duckcloud.info';
async function get<T>(path:string, revalidate=600):Promise<T|null>{try{const response=await fetch(`${base}${path}`,{next:{revalidate,tags:['cms']}});if(!response.ok)return null;const json=await response.json() as {data:T};return json.data;}catch{return null;}}
export async function getArticles(page=1){const data=await get<{results:CmsArticle[]}>(`/v1/articles?page=${page}&limit=12`,300);return data?.results??[];}
export const getArticle=(slug:string)=>get<CmsArticle>(`/v1/articles/${encodeURIComponent(slug)}`,300);
export async function getCategories(){const data=await get<{results:Array<{id:string;slug:string;name:string;description?:string}>}>('/v1/categories',1800);return data?.results??[];}

export function markdownToHtml(markdown:string):{html:string;toc:Array<{id:string;text:string;level:number}>} {
  const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
  const ids=new Map<string,number>(),toc:Array<{id:string;text:string;level:number}>=[];
  const inline=(s:string)=>escape(s).replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" rel="noopener noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>');
  const html=markdown.split(/\n{2,}/).map(block=>{const raw=block.trim(),heading=raw.match(/^(#{1,3})\s+(.+)$/);if(heading){const level=heading[1].length,label=heading[2],base=label.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'section',n=ids.get(base)||0,id=n?`${base}-${n+1}`:base;ids.set(base,n+1);if(level>=2)toc.push({id,text:label,level});return `<h${level} id="${id}">${inline(label)}</h${level}>`}const fence=raw.match(/^```([a-z0-9+#.-]*)\n([\s\S]*?)\n?```$/i);if(fence){const language=escape(fence[1]||'text');return `<figure class="code-block"><figcaption>${language}</figcaption><pre tabindex="0"><code class="language-${language}">${escape(fence[2])}</code></pre></figure>`}if(/^---+$/.test(raw))return'<hr>';const lines=raw.split('\n');if(lines.every(x=>/^[-*]\s+/.test(x)))return`<ul>${lines.map(x=>`<li>${inline(x.replace(/^[-*]\s+/,''))}</li>`).join('')}</ul>`;if(lines.every(x=>/^\d+\.\s+/.test(x)))return`<ol>${lines.map(x=>`<li>${inline(x.replace(/^\d+\.\s+/,''))}</li>`).join('')}</ol>`;if(lines.every(x=>/^>\s?/.test(x)))return`<blockquote>${lines.map(x=>inline(x.replace(/^>\s?/,''))).join('<br>')}</blockquote>`;return `<p>${lines.map(inline).join('<br>')}</p>`;}).join('');return{html,toc};
}
