#!/bin/bash
# Duck Cloud Website - Command Reference Guide

echo "🦆 Duck Cloud - Command Reference Guide"
echo "========================================"
echo ""
echo "📋 COMMON COMMANDS:"
echo ""
echo "1️⃣  Development"
echo "   npm run dev              Start development server"
echo "   npm run dev -- -p 3001   Run on different port"
echo ""
echo "2️⃣  Production"
echo "   npm run build            Build for production"
echo "   npm start                Start production server"
echo ""
echo "3️⃣  Code Quality"
echo "   npm run lint             Run ESLint"
echo "   npm run format           Format with Prettier"
echo "   npm run type-check       Check TypeScript types"
echo ""
echo "4️⃣  Installation"
echo "   npm install              Install dependencies"
echo "   npm ci                   Clean install"
echo ""
echo "5️⃣  Maintenance"
echo "   npm update               Update packages"
echo "   npm outdated             Check outdated packages"
echo "   npm audit                Check security issues"
echo ""
echo "📁 USEFUL SHORTCUTS:"
echo ""
echo "File Locations:"
echo "  Products:     src/utils/data.ts"
echo "  Colors:       tailwind.config.ts"
echo "  Navigation:   src/components/Navbar.tsx"
echo "  Home:         src/app/page.tsx"
echo "  Styles:       src/app/globals.css"
echo ""
echo "📖 DOCUMENTATION:"
echo ""
echo "  START_HERE.md            - Begin here"
echo "  README.md                - Main documentation"
echo "  SETUP.md                 - Setup & deployment"
echo "  DEVELOPMENT.md           - Developer guide"
echo "  QUICK_REFERENCE.md       - Quick lookup"
echo "  API_INTEGRATION.md       - API examples"
echo ""
echo "🚀 QUICK START:"
echo ""
echo "  1. npm install"
echo "  2. npm run dev"
echo "  3. Open http://localhost:3000"
echo ""
echo "✨ Pro Tips:"
echo ""
echo "  • Press Ctrl+C to stop dev server"
echo "  • Use npm run format before committing"
echo "  • Check types with npm run type-check"
echo "  • Read QUICK_REFERENCE.md for shortcuts"
echo ""
echo "📞 Need Help?"
echo ""
echo "  • Read: START_HERE.md (getting started)"
echo "  • Read: QUICK_REFERENCE.md (cheat sheet)"
echo "  • Read: DEVELOPMENT.md (architecture)"
echo ""
