import type {DnsType} from '../types';
const DOMAIN=/^(?=.{1,253}\.?$)(?!-)(?:[a-z\d](?:[a-z\d-]{0,61}[a-z\d])?\.)+[a-z](?:[a-z\d-]{0,61}[a-z\d])?\.?$/i;
const V4=/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;
export function validateDomain(value:string){const d=value.trim().toLowerCase().replace(/\.$/,'');if(!DOMAIN.test(d))throw apiError('INVALID_DOMAIN','Enter a valid public domain name.');return d}
export function validateDnsType(value:string):DnsType{const type=value.toUpperCase();if(!['A','AAAA','CNAME','MX','TXT','NS'].includes(type))throw apiError('INVALID_DNS_TYPE','Supported record types are A, AAAA, CNAME, MX, TXT, and NS.');return type as DnsType}
export function isPrivateIp(ip:string){ip=ip.replace(/^\[|\]$/g,'');const m=ip.match(V4);if(m){const [a,b,c]=m.slice(1).map(Number);if([a,b,c,Number(m[4])].some(x=>x>255))return true;return a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127||a===198&&(b===18||b===19)||a===192&&b===0&&c===0||a===192&&b===0&&c===2||a===198&&b===51&&c===100||a===203&&b===0&&c===113}
 const x=ip.toLowerCase().split('%')[0];return x==='::'||x==='::1'||x.startsWith('fc')||x.startsWith('fd')||/^fe[89ab]/.test(x)||x.startsWith('2001:db8:')||x.startsWith('::ffff:127.')||x.startsWith('::ffff:10.')||x.startsWith('::ffff:192.168.');}
export function validateUrl(value:string){if(value.length>2048)throw apiError('URL_TOO_LONG','URL must be 2,048 characters or fewer.');let u:URL;try{u=new URL(value)}catch{throw apiError('INVALID_URL','Enter a valid public HTTP or HTTPS URL.')}if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.port)throw apiError('INVALID_URL','Only public HTTP or HTTPS URLs on standard ports are allowed.');const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.localhost')||h==='metadata.google.internal'||h.endsWith('.internal')||isPrivateIp(h))throw apiError('PRIVATE_TARGET','Private, local, reserved, and metadata targets are not allowed.');return u}
export function apiError(code:string,message:string){return Object.assign(new Error(message),{code}) as Error&{code:string}}
